### ISSUE TITLE
Business cards

### ISSUE THREAD

**Issue by michalmikolajczyk** [VIKING-GARAGE/operations#1]
**Is your feature request related to a problem? Please describe.**
I don't have business cards on business meetings, and people are kind of expecting them.

**Describe the solution you'd like**
I would like to get a set of PDF files with a new stylish business card

**Describe alternatives you've considered**
instead we could use
- linkedIn
- QR code with our data
<img width="251" alt="screen shot 2018-06-28 at 11 21 14 am" src="https://user-images.githubusercontent.com/1655227/42025663-6b10f17c-7ac5-11e8-82d0-8cebcf99bd4a.png">

**Additional context**
Business cards are classic and we really need them. They must be completed before the end of the day so they can be printed on time.

**Comment by lam3lka** [comment]
Need it before 12 CEST

**Comment by lam3lka** [comment]
Who close the issue?

**Comment by michalmikolajczyk** [comment]
or actually, the files were sent over email, so I should assign the task to you with that information, and you should close it :)
