### ISSUE TITLE
Key words research

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#10]
I don't know what key words are the most often used by our customers and which we should use in our content campaigns.

I need a list with the most frequently used by our customers key words and proposals of topics to each key word. 

Alternatives:
- we can use key words from Adwords campaign planner: https://docs.google.com/spreadsheets/d/16ncHYbcOQs2N2Yyc7m2ULNpcKegcbW4SY5jFxdYKJ8o/edit#gid=416316026
- we can look for articles of our competition (as benchmarks)

**Comment by lam3lka** [comment]
Done here: https://docs.google.com/spreadsheets/d/1v5YVD2Y-wwRyOOv5wgxtXnxYwwUL2ArA_5mH3yS3jLE/edit#gid=847111042

**Comment by michalmikolajczyk** [comment]
looks solid!
