### ISSUE TITLE
Create e-mail templates for Bike Owners on each step of the process

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#19]
**Is your feature request related to a problem? Please describe.**
We want to focus on Customer experience #2: fast responses, empathy - we are above expectations in Phase 2. E-mail templates can help us achieve this goal.

**Describe the solution you'd like**
I would like to create e-mail templates for Bike Owners to make sure that our responses will be fast and our process will be easy to understand for Bike Owners. It will also help us set expectations toward Bike Owners at the beginning of our journey together.

**Describe alternatives you've considered**
Video with the explained step-by-step process. 
Whatsapp messages (we can use e-mail templates in WhatsApp).

**Additional context**

**Comment by michalmikolajczyk** [comment]
@lam3lka there is no task description

I don't understand how that helps meet the goal for this phase?

**Comment by lam3lka** [comment]
@michalmikolajczyk updated

**Comment by michalmikolajczyk** [comment]
thank you @lam3lka. Where are the templates created?
