### ISSUE TITLE
Create strategy | GAP | ASEAN markets

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#2]
Please, find the strategy in the document below.

**Comment by michalmikolajczyk** [comment]
@lam3lka thanks. 
https://docs.google.com/document/d/1G0oCoBGh44Z1HWr6Qb-IzUA_6w-XouLPUaBtITVyIFE/edit

**Comment by lam3lka** [comment]
Let me know if we can close the issue @michalmikolajczyk

**Comment by michalmikolajczyk** [comment]
yep
