### ISSUE TITLE
Create e-mail templates for Customers on each step of Journey

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#21]
**Is your feature request related to a problem? Please describe.**
We do not have any processes for Customers. It can be also hard for them to follow our flow without any additional help from the VG team.

**Describe the solution you'd like**
Create e-mail templates, so when they will sign up, we will help them go smoothly through our flow and enhance their experience. 

**Describe alternatives you've considered**
Templates in Mailchimps (more complicated, not that personalized) or just stay in touch with them on whatsapp.

**Additional context**
Add any other context or screenshots about the feature request here like Hootsuite (there are similar, for free).

**Comment by lam3lka** [comment]
Let's finish it here: https://docs.google.com/document/d/16Bhix1grZBomsVM82cWWw2z-6Jz3ziUXx7Fs3SWGv6A/edit?usp=sharing

**Comment by michalmikolajczyk** [comment]
Please use the standard Github issue template for new features so we can understand better what is the purpose of this task.

**Comment by michalmikolajczyk** [comment]
@lam3lka

**Comment by lam3lka** [comment]
@michalmikolajczyk done.

**Comment by michalmikolajczyk** [comment]
@lam3lka thank you for the edit.

it looks good! I will familiarise myself with the onboarding document

**Comment by yangzhisiang** [comment]
https://docs.google.com/document/d/1qzj5A764iTr9be50aNugu12K5UZSLD47vf2J1BnEP2Y/edit

**Comment by michalmikolajczyk** [comment]
that's done, right?
