### ISSUE TITLE
Delete urls with errors from Google Search Console

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#26]
**Describe the bug**
Google Search Console reported 4 urls with errors (404, page not found) on our website, they come from the older version. 

**To Reproduce**
Go to: https://www.google.com/webmasters/tools/crawl-errors?siteUrl=https://www.vikinggarage.com/&utm_source=wnc_655201&utm_medium=gamma&utm_campaign=wnc_655201&utm_content=msg_717100&hl=pl#t2=5
and fix it, please.

**Expected behavior**
I don't want to see any errors reported by GSC ;D

**Screenshots**

<img width="1195" alt="zrzut ekranu 2018-07-16 o 20 45 17" src="https://user-images.githubusercontent.com/28931514/42762808-d910d674-8943-11e8-8ef0-952d74f6687b.png">

**Comment by lam3lka** [comment]
https://support.google.com/webmasters/answer/93710

**Comment by michalmikolajczyk** [comment]
That is well-described task!

- those pages are from the old site. Do we still have any links to them?

**Comment by lam3lka** [comment]
Yes, I forwarded the e-mail to you. Also, when you log to Search Console you will see 4 reported links from the old website.

**Comment by lam3lka** [comment]
Done.

**Comment by michalmikolajczyk** [comment]
🙌
