### ISSUE TITLE
Connect Wix landing page with VG domain

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#27]
**Is your feature request related to a problem? Please describe.**
In order to launch the landing page dedicated to bike owners we need to connect the website with partner.vikinggarage.com domain. 

**Describe the solution you'd like**
I want you Michał to connect domain with the website. I already transfer you the rights to the website – it is necessary to connect it. 

Here is the answer from Wix support team: 

> I have checked your account under email joanna.k@onet.pl and can see that the site you are referring to is in another account, under email michal@vikinggarage.com.  I assume you have transferred the site VIKING GARAGE to a different account, that's why you are a contributor of the site. In order to connect the site to the domain and verify ownership, you need to be the owner of the site and the site should be assigned to the Premium plan.

> 

**Describe alternatives you've considered**
1. Give me adress to GoDaddy and I can do it by myself.
2. We can use corrent domain, but it's unprofessional.

**Comment by michalmikolajczyk** [comment]
@lam3lka thank you for the edit.

please:
- [ ] change your email
- [ ] provide me with the IP that I should point the domain to, I will point partners.vikinggarage.com (if it's even required as it already points at Wix) 

so the url will be something like https://partners.vikinggarage.com/vikinggarage or perhaps we could just use https://partners.vikinggarage.com

what do you think?
