### ISSUE TITLE
Discussion on domain adress

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#29]
**Is your feature request related to a problem? Please describe.**
I am not sure if we should change our domain address: https://www.vikinggarage.com on https://vikinggarage.com. 

Right now, more results are generated with https://www.vikinggarage.com

<img width="739" alt="zrzut ekranu 2018-07-27 o 00 17 31" src="https://user-images.githubusercontent.com/28931514/43308446-36b3d060-91b4-11e8-957b-984292c7ee56.png">

While https://vikinggarage.com it's only 2000 results:

<img width="836" alt="zrzut ekranu 2018-07-27 o 15 47 41" src="https://user-images.githubusercontent.com/28931514/43308539-833feb80-91b4-11e8-9191-cc8f9c8cf917.png">

**Describe the solution you'd like**
I just want to have a discussion on that topic and then let's see what are the solutions.

**Describe alternatives you've considered**
So, we have two:
https://vikinggarage.com
or
https://www.vikinggarage.com

**Comment by michalmikolajczyk** [comment]
there is no gain. I like www prefix. if you want to change, please give arguments for the change, otherwise I would suggest to focus on more potent tasks.

**Comment by lam3lka** [comment]
Yes, www prefix it better I agree!
