### ISSUE TITLE
Set up VIKING GARAGE on ShareTribe - upgrade to Pro Plan

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#3]
To start using ShareTribe we need to buy a Pro Plan (https://www.sharetribe.com/pricing.html).

**Comment by michalmikolajczyk** [comment]
@lam3lka I will need admin access to the platform I think.

The points below are the blockers I see:
- [x] Facebook app to use for login is in dev mode (please give me admin rights)
- [x] Blog still redirect to wiki (let's disable that link for now)
- [x] the page "how it works" is empty
- [x] let's perhaps add WhatsApp to the Contact page?

**Comment by lam3lka** [comment]
Contact details (e-mail & whatsapp) added to About and How it works pages
