### ISSUE TITLE
Setup Google Analytics – ShareTribe

### ISSUE THREAD

**Issue by lam3lka** [VIKING-GARAGE/operations#5]

**Comment by michalmikolajczyk** [comment]
@lam3lka what is the status of this task?

**Comment by lam3lka** [comment]
- [x] track searches

- [x] events tracking

1. Listing view
2. Book button clicked
3. Listing
4. Initiate preauthorized transaction
5. Account confirmed
6. SignedUp

**Comment by lam3lka** [comment]
Still need to set up below events: 

- [x] user signs up with email

- [x] user signs up with Facebook Connect

- [x] user deletes their account

- [x] user creates a new listing

- [x] user posts a new message in a conversation or transaction thread

- [x] user go through the paid transaction flow: (preauthorize, accepts, rejects, redirect to PayPal...)

- [x] Transaction done (Thank you page)

**Comment by lam3lka** [comment]
Okay, I am blocked – I am waiting for the response from ShareTribe team in terms of listed events.

**Comment by michalmikolajczyk** [comment]
thanks for the update, we wait

**Comment by lam3lka** [comment]
- [x] Connect Adwords and GA

- [x] Add goals in GA

**Comment by michalmikolajczyk** [comment]
@lam3lka what is the status of this task?

**Comment by michalmikolajczyk** [comment]
🙌
